# -*- coding: utf-8 -*-
"""Emma Watson.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rmikIPfPKgYZJMWvd19T-FRlMwFZ1y-V
"""

api_key='316221157e2b45d88471d33ec5f6c211'

pip install pytube

from pytube import YouTube
vedio=YouTube("https://www.youtube.com/watch?v=jZyACElLUyA")
yt=vedio.streams.get_audio_only()

yt.download()

import os
current_dir=os.getcwd()
for file in os.listdir(current_dir):
  if file.endswith(".mp4"):
    mp4_file=os.path.join(current_dir,file)
    print(mp4_file)

import sys
import time
import requests
 
filename=mp4_file
def read_file(filename,chunk_size=5342880):
  with open(filename,'rb') as _file:
    while True:
      data = _file.read(chunk_size)
      if not data:
        break
      yield data
headers={'authorization': api_key}
response=requests.post('https://api.assemblyai.com/v2/upload',
                       headers=headers,
                       data=read_file(filename))
audio_url=response.json()['upload_url']
print(audio_url)

import requests
endpoint="https://api.assemblyai.com/v2/transcript"
json ={
    "audio_url": audio_url
}
headers = {
    "authorization":api_key,
    "content-type":"application/json"
}
transcript_input_response=requests.post(endpoint,json=json,headers=headers)
print(transcript_input_response.json())

transcript_id=transcript_input_response.json()["id"]
transcript_id

import requests
endpoint=f"https://api.assemblyai.com/v2/transcript/{transcript_id}"

headers={
    "authorization":api_key,
}
transcript_output_response=requests.get(endpoint,headers=headers)

transcript_output_response.json()["status"]

transcript_output_response.json()

transcript_output_response.json()["text"]